---
- name: 1.0.0 PostgreSQL Advanced Configuration & Benchmarking
  hosts: postgres_servers
  become: true
  vars:
    postgresql_version: "16"
    pg_conf_dir: "/etc/postgresql/{{ postgresql_version }}/main"
    pg_data_dir: "/pg_data/16"
    bench_db: "bench"
    bench_user: "pgbench"
    bench_password: "123" # Пароль для пользователя pgbench
    replication_user: "replicator"
    replication_password: "123" # Пароль для репликации


  tasks:

    # ========================================================================
    # Предварительная проверка: Убедиться, что PostgreSQL запущен
    # ========================================================================
    - name: Ensure PostgreSQL cluster is running
      command: pg_ctlcluster {{ postgresql_version }} main start
      register: pg_start_result
      changed_when: "'is already online' not in pg_start_result.stderr and pg_start_result.rc == 0"
      failed_when: false # Не останавливать плейбук, если старт не удался (пойдет дальше и упадет на подключении, где ошибка будет понятнее)
      # Или более строгий вариант с systemd:
      # systemd:
      #  name: postgresql
      #  state: started

    - name: Wait for PostgreSQL to be ready
      wait_for:
        port: 5432
        timeout: 30
      when: pg_start_result.rc == 0 or pg_start_result.rc is undefined


    # ========================================================================
    # 1.0. Создать пользователя pgbench и базу данных bench
    # ========================================================================
    - name: 1.0 Create database bench
      become_user: postgres
      command: psql -c "CREATE DATABASE {{ bench_db }};"
      args:
        creates: "/var/lib/postgresql/.createdb_{{ bench_db }}" # Хак для идемпотентности, либо проверять наличие
      register: db_created
      changed_when: "'already exists' not in db_created.stderr"
      failed_when: db_created.rc != 0 and 'already exists' not in db_created.stderr

    # способ проверки создания БД
    - name: Check if database exists
      become_user: postgres
      shell: "psql -lqt | cut -d \\| -f 1 | grep -qw {{ bench_db }}"
      register: db_check
      changed_when: false
      failed_when: false

    - name: Create database bench (if not exists)
      become_user: postgres
      command: psql -c "CREATE DATABASE {{ bench_db }};"
      when: db_check.rc != 0

    - name: Create user pgbench
      become_user: postgres
      command: psql -c "CREATE USER {{ bench_user }} WITH PASSWORD '{{ bench_password }}';"
      register: user_created
      changed_when: "'already exists' not in user_created.stderr"
      failed_when: user_created.rc != 0 and 'already exists' not in user_created.stderr

    - name: Grant privileges to pgbench on bench DB
      become_user: postgres
      command: psql -d {{ bench_db }} -c "GRANT ALL PRIVILEGES ON DATABASE {{ bench_db }} TO {{ bench_user }};"

    - name: Grant schema privileges
      become_user: postgres
      command: psql -d {{ bench_db }} -c "GRANT ALL ON SCHEMA public TO {{ bench_user }};"

    # ========================================================================
    # 1.1. Подключить модули (pg_stat_statements и другие)
    # ========================================================================
    - name: 1.1 Install additional PostgreSQL modules
      apt:
        name:
          - "postgresql-contrib-{{ postgresql_version }}"
        state: present

    - name: Add pg_stat_statements to shared_preload_libraries
      lineinfile:
        path: "{{ pg_conf_dir }}/postgresql.conf"
        regexp: "^#?shared_preload_libraries"
        line: "shared_preload_libraries = 'pg_stat_statements'"
        state: present

    - name: Configure pg_stat_statements params
      blockinfile:
        path: "{{ pg_conf_dir }}/postgresql.conf"
        marker: "# {mark} ANSIBLE PG_STAT_STATEMENTS"
        block: |
          pg_stat_statements.max = 10000
          pg_stat_statements.track = all

    # ========================================================================
    # 1.2. Настроить логирование всех запросов
    # ========================================================================
    - name: 1.2 Configure logging - log_statement
      lineinfile:
        path: "{{ pg_conf_dir }}/postgresql.conf"
        regexp: "^#?log_statement"
        line: "log_statement = 'all'"
        state: present

    - name: Configure logging - log_duration
      lineinfile:
        path: "{{ pg_conf_dir }}/postgresql.conf"
        regexp: "^#?log_duration"
        line: "log_duration = on"
        state: present

    - name: Configure logging - log_min_duration_statement
      lineinfile:
        path: "{{ pg_conf_dir }}/postgresql.conf"
        regexp: "^#?log_min_duration_statement"
        line: "log_min_duration_statement = 0"
        state: present

    - name: Configure logging - log_line_prefix
      lineinfile:
        path: "{{ pg_conf_dir }}/postgresql.conf"
        regexp: "^#?log_line_prefix"
        line: "log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '"
        state: present

    # ========================================================================
    # Перезагрузка PostgreSQL для применения настроек (shared_preload_libraries требует рестарта)
    # ========================================================================
    - name: Restart PostgreSQL to apply changes
      command: pg_ctlcluster {{ postgresql_version }} main restart
      changed_when: true

    - name: Wait for PostgreSQL to be ready after restart
      wait_for:
        port: 5432
        timeout: 30

    # Создание расширения внутри БД
    - name: Create extension pg_stat_statements in bench DB
      become_user: postgres
      command: psql -d {{ bench_db }} -c "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;"

    # ========================================================================
    # 1.3. Нагрузочное тестирование с помощью pgbench
    # ========================================================================
    - name: 1.3 Initialize pgbench schema
      become_user: postgres
      command: >
        pgbench -i -s 10 {{ bench_db }}
      environment:
        PGPASSWORD: "{{ bench_password }}"
      # Примечание: pgbench -i обычно запускается от суперпользователя или владельца БД. (я тоже гей, ведь кирилл слушает тимати)
      # Если pgbench пользователь еще не имеет прав на создание таблиц, запускаем от postgres.
      # Для теста подключимся как pgbench позже.

    - name: Run pgbench benchmark (simple select)
      become_user: postgres
      command: >
        pgbench -c 4 -j 2 -t 100 {{ bench_db }}
      register: pgbench_result
      ignore_errors: true # Чтобы playbook не упал, если будут ошибки, но результат нам нужен

    - name: Display pgbench results
      debug:
        var: pgbench_result.stdout_lines

    # ========================================================================
    # 1.4. Получить список самых ресурсоемких запросов из pg_stat_statements
    # ========================================================================
    - name: 1.4 Get top 5 IO heavy queries (write)
      become_user: postgres
      command: >
        psql -d {{ bench_db }} -c "
        SELECT query, calls, total_exec_time, mean_exec_time, 
               shared_blks_written, blk_write_time
        FROM pg_stat_statements 
        ORDER BY blk_write_time DESC NULLS LAST 
        LIMIT 5;"
      register: top_io_queries
      changed_when: false

    - name: Display Top IO Queries
      debug:
        var: top_io_queries.stdout_lines

    - name: Get top 5 longest queries (execution time)
      become_user: postgres
      command: >
        psql -d {{ bench_db }} -c "
        SELECT query, calls, total_exec_time, mean_exec_time 
        FROM pg_stat_statements 
        ORDER BY total_exec_time DESC 
        LIMIT 5;"
      register: top_time_queries
      changed_when: false

    - name: Display Top Time Queries
      debug:
        var: top_time_queries.stdout_lines

    # ========================================================================
    # 1.5. Показать в логах, что делал pgbench
    # ========================================================================
    - name: 1.5 Show recent logs related to pgbench
      shell: |
        grep "pgbench" /var/log/postgresql/postgresql-{{ postgresql_version }}-main.log | tail -n 20
      register: pgbench_logs
      changed_when: false
      ignore_errors: true # Файл логов может быть пуст или повернут

    - name: Display pgbench logs
      debug:
        var: pgbench_logs.stdout_lines

    # ========================================================================
    # 1.6. Создать пользователя для репликации
    # ========================================================================
    - name: 1.6 Create replication user
      become_user: postgres
      command: >
        psql -c "CREATE USER {{ replication_user }} WITH REPLICATION ENCRYPTED PASSWORD '{{ replication_password }}';"
      register: repl_user_created
      changed_when: "'already exists' not in repl_user_created.stderr"
      failed_when: repl_user_created.rc != 0 and 'already exists' not in repl_user_created.stderr

    # ========================================================================
    # 1.7. Настроить доступы (pg_hba.conf) для подключения с другой виртуалки
    # ========================================================================
    - name: 1.7 Allow replication connections from subnet
      blockinfile:
        path: "{{ pg_conf_dir }}/pg_hba.conf"
        marker: "# {mark} ANSIBLE REPLICATION ACCESS"
        block: |
          # Allow replication from local network
          host    replication     {{ replication_user }}    192.168.122.0/24       scram-sha-256
          host    all             all             192.168.122.0/24       scram-sha-256

    - name: Reload PostgreSQL to apply HBA changes
      command: pg_ctlcluster {{ postgresql_version }} main reload
      changed_when: true

    - name: Final Status
      debug:
        msg: "Task 1 completed successfully! User {{ bench_user }}, DB {{ bench_db }}, Replication user {{ replication_user }} created."